apiVersion: v1
kind: Secret
metadata:
  name: repository-pat
  namespace: wac-hospital

type: Opaque
stringData:
  username: <your-acount> # zvyčajne môže byť akékoľvek meno
  password: <your-personal-access-token>  # vygenerovaný PAT